language: rust
rust: nightly

if: (branch = staging OR branch = trying OR branch = master) OR (type = pull_request AND branch = master)

script:
  - cargo check

cache: cargo

notifications:
  email:
    on_success: never
